on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Fix temp dir
        run: |
          export TMPDIR=$PWD/tmp
          mkdir -p $TMPDIR
          python3 -m venv venv
          ./venv/bin/pip install --no-cache-dir -r requirements.txt

      - name: Run app
        run: |
          source venv/bin/activate
          python main.py