on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [self-hosted, proxmox]

    steps:
      - uses: actions/checkout@v4

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Setup venv smart
        run: |
          if [ ! -d "venv" ]; then
            python3 -m venv venv
          fi
          ./venv/bin/pip install -r requirements.txt

      - name: Run app
        run: ./venv/bin/python main.py
