on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [self-hosted, proxmox]

    steps:
          - name: Pull latest code
            run: |
              cd /root/homelab-ai
              git fetch origin
              git reset --hard origin/main
    
          - name: Install deps (if needed)
            run: |
              cd /root/homelab-ai
              if [ ! -d "venv" ]; then
                python3 -m venv venv
              fi
              ./venv/bin/pip install --no-cache-dir -r requirements.txt
    
          - name: Restart API
            run: |
              systemctl restart homelab-api
